name: Scrape
description: Scrape

runs:
  using: node24
  main: dist/index.js

inputs:
  AMAZING_TOKEN:
    description: AMAZING_TOKEN
    required: true

  AMAZING_PRIVATE_CHAT_ID:
    description: AMAZING_PRIVATE_CHAT_ID
    required: true

  AMAZING_DEVOPS_CHAT_ID:
    description: AMAZING_DEVOPS_CHAT_ID
    required: true

  AMAZING_DOTNET_CHAT_ID:
    description: AMAZING_DOTNET_CHAT_ID
    required: true

  AMAZING_FRONTEND_CHAT_ID:
    description: AMAZING_FRONTEND_CHAT_ID
    required: true

outputs:
  COMMIT_MESSAGE:
    description: COMMIT_MESSAGE
