name: Amazing

on:
  push:
    paths:
      - dist/index.js
      - data/errors.json
  schedule:
    - cron: 42 */2 * * *

jobs:
  Scrape:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v7

      - id: scrape
        name: Scrape
        uses: ./
        with:
          AMAZING_TOKEN: ${{ secrets.AMAZING_TOKEN }}
          AMAZING_PRIVATE_CHAT_ID: ${{ vars.AMAZING_PRIVATE_CHAT_ID }}
          AMAZING_DOTNET_CHAT_ID: ${{ vars.AMAZING_DOTNET_CHAT_ID }}
          AMAZING_FRONTEND_CHAT_ID: ${{ vars.AMAZING_FRONTEND_CHAT_ID }}

      # https://github.com/marketplace/actions/add-commit
      - name: Commit
        uses: EndBug/add-and-commit@v10
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        with:
          add: data
          message: ${{ steps.scrape.outputs.COMMIT_MESSAGE }}
